version: '3.8'

services:
  bot:
    build: ./docker/php/
    command: sh -c "sleep 10 && cd /app && php vendor/bin/phinx migrate && php /app/bot.php" # рабочий вариант
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_NAME=${DB_NAME}
#      - DB_USERNAME=${DB_USERNAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_PORT=3306
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 5s
      retries: 3